export const copy = {
  de: {
    eyebrow: 'EIN HANDY. DEIN TEAM.', title: 'DEIN TEAM.\nDEINE PARTY.',
    intro: 'Fußballwissen trifft Party. Wer blufft am besten – und wer behält die Nerven?',
    choose: 'WÄHL DEIN SPIEL', players: '3–10 Spieler', onePhone: 'Ein gemeinsames Handy',
    imposter: 'IMPOSTER', bomb: 'BOMBE',
    imposterDescription: 'Ein Name. Ein Geheimnis. Entlarvt die Imposter in eurem Team.',
    bombDescription: 'Nenn einen Fußballer und gib das Handy weiter. Die Zeit läuft …',
    bluff: 'BLUFF & FUSSBALLWISSEN', speed: 'TEMPO & NERVEN',
    start: 'Team aufstellen', back: 'Zurück', team: 'DEIN TEAM',
    teamIntro: 'Tragt eure Namen ein. Danach wandert das Handy von Spieler zu Spieler.',
    name: 'Spielername', namePlaceholder: 'Wie heißt du?', add: 'Hinzufügen', remove: 'Entfernen',
    emptyTeam: 'Der erste Platz ist noch frei.', emptyTeamHint: 'Wer ist heute dabei?',
    empty: 'Gib einen Namen ein.', duplicate: 'Dieser Name ist schon im Team.', full: 'Dein Team ist voll: maximal 10 Spieler.',
    difficulty: 'FUSSBALLWISSEN', easy: 'Leicht', medium: 'Mittel', hard: 'Schwer',
    easyHint: 'Weltstars & berühmte Legenden', mediumHint: 'Bekannte Topspieler & Legenden', hardHint: 'Bekannte Profis aus den Top-5-Ligen',
    imposters: 'IMPOSTER', impostersHint: 'Die anderen sehen denselben Fußballernamen.',
    oneKnows: 'Mindestens ein Mitspieler kennt den Fußballernamen.',
    bombHint: 'Ihr habt 60 Sekunden. Nennt passende Fußballer und reicht das Handy weiter. Wer es bei der Explosion hält, ist raus.',
    legends: 'AKTIVE SPIELER + LEGENDEN',
    review: 'Aufstellung ansehen', needPlayers: 'Mindestens 3 Spieler – maximal 10.',
    lineup: 'AUFSTELLUNG STEHT!', lineupHint: 'Ein Team. Ein Handy. Ein guter Abend.',
    mode: 'Spielmodus', level: 'Schwierigkeit', edit: 'Team bearbeiten', home: 'Zur Startseite',
    noHint: 'Ohne Hinweis', singleRound: 'Einzelne Runde',
    rules: 'Euer Spiel', imposterRules: 'Die Mitspieler erhalten denselben Namen eines aktiven Fußballers oder einer Legende. Imposter erhalten keinen Namen. Wählt vorher, ob sie einen Hinweis bekommen.',
    bombRules: 'Eine zufällige Frage passend zur Schwierigkeit, passende Fußballernamen und genau 60 Sekunden. Wer das Handy bei der Explosion hält, scheidet aus.',
    language: 'Sprache wählen', footballArt: 'Eigene Chibi-Maskottchen von Footy Party',
  },
  en: {
    eyebrow: 'ONE PHONE. YOUR TEAM.', title: 'YOUR TEAM.\nYOUR PARTY.',
    intro: 'Football knowledge meets party night. Who can bluff – and who can keep their cool?',
    choose: 'PICK YOUR GAME', players: '3–10 players', onePhone: 'One shared phone',
    imposter: 'IMPOSTER', bomb: 'BOMB',
    imposterDescription: 'One name. One secret. Find the imposters hiding in your team.',
    bombDescription: 'Name a footballer and pass the phone. The clock is ticking …',
    bluff: 'BLUFF & FOOTBALL KNOWLEDGE', speed: 'SPEED & NERVES',
    start: 'Build your team', back: 'Back', team: 'YOUR TEAM',
    teamIntro: 'Enter your names. Then pass the phone from player to player.',
    name: 'Player name', namePlaceholder: 'What’s your name?', add: 'Add player', remove: 'Remove',
    emptyTeam: 'The first spot is waiting.', emptyTeamHint: 'Who’s playing tonight?',
    empty: 'Enter a name.', duplicate: 'This name is already on your team.', full: 'Your team is full: 10 players maximum.',
    difficulty: 'FOOTBALL KNOWLEDGE', easy: 'Easy', medium: 'Medium', hard: 'Hard',
    easyHint: 'World stars & famous legends', mediumHint: 'Well-known top players & legends', hardHint: 'Recognisable pros from the top five leagues',
    imposters: 'IMPOSTERS', impostersHint: 'Everyone else sees the same footballer’s name.',
    oneKnows: 'At least one teammate knows the footballer’s name.',
    bombHint: 'You have 60 seconds. Name matching footballers and pass the phone. Whoever holds it at the explosion is out.',
    legends: 'ACTIVE PLAYERS + LEGENDS',
    review: 'View line-up', needPlayers: 'At least 3 players – up to 10.',
    lineup: 'LINE-UP READY!', lineupHint: 'One team. One phone. One great night.',
    mode: 'Game mode', level: 'Difficulty', edit: 'Edit team', home: 'Back to home',
    noHint: 'No hints', singleRound: 'Single round',
    rules: 'Your game', imposterRules: 'Teammates receive the same name of an active footballer or a legend. Imposters receive no name. Choose beforehand whether they get a hint.',
    bombRules: 'A random question matching your difficulty, footballer names and exactly 60 seconds. Whoever holds the phone when it explodes is out.',
    language: 'Choose language', footballArt: 'Original Footy Party chibi mascots',
  },
} as const;
