export const gameCopy = {
  de: {
    start: 'Spiel starten', again: 'Nochmal spielen', next: 'Weiter',
    card: 'Karte aufdecken', swipe: 'Nach oben wischen', hide: 'Wieder zudecken',
    pass: 'Gib das Handy an', onlyYou: 'Nur du schaust auf den Bildschirm.',
    footballer: 'DEIN FUSSBALLER', imposter: 'DU BIST IMPOSTER',
    hideFirst: 'Decke deine Karte wieder zu, bevor du das Handy weitergibst.',
    swipeFirst: 'Wische die Karte hoch und merke dir deine Rolle.',
    continue: 'Deine Karte ist verdeckt. Weiter zum nächsten Spieler.',
    ready: 'ALLE KENNEN IHRE ROLLE.', discuss: 'Jetzt seid ihr dran! Gebt Hinweise, diskutiert und ratet in eurer Gruppe.',
    unmask: 'Imposter aufdecken', impostersWere: 'DIE IMPOSTER WAREN',
    back: 'Zurück zum Team', cancel: 'Runde beenden', cancelTitle: 'Runde wirklich beenden?',
    cancelHint: 'Diese Runde wird beendet. Eure Namen und Einstellungen bleiben erhalten.',
    cancelNo: 'Weiterspielen', cancelYes: 'Runde beenden',
    bombReady: '60 SEKUNDEN. EIN TEAM.', bombIntro: 'Nennt passende Fußballer und reicht das Handy weiter. Die Frage erscheint beim Start.',
    soundTest: 'Ton testen', soundHint: 'Lautstärke an. Lasst den Browser während der Runde geöffnet.',
    soundError: 'Ton konnte nicht gestartet werden. Teste den Ton und versuche es erneut.',
    soundRequired: 'Vor dem Start wird der Ton für diese Runde aktiviert.',
    running: 'DIE BOMBE LÄUFT', passBomb: 'Antwort nennen. Handy weitergeben!',
    finished: 'BOOM!', out: 'Wer das Handy hält, ist raus.',
    time: 'Verbleibende Zeit', loading: 'Ton wird aktiviert …',
    bombEasy: 'Vereine & Nationalitäten', bombMedium: 'Nationalität + Position', bombHard: 'Teamkollegen & Karrierewissen',
  },
  en: {
    start: 'Start game', again: 'Play again', next: 'Next',
    card: 'Reveal card', swipe: 'Swipe up', hide: 'Cover again',
    pass: 'Pass the phone to', onlyYou: 'Only you should look at the screen.',
    footballer: 'YOUR FOOTBALLER', imposter: 'YOU ARE THE IMPOSTER',
    hideFirst: 'Cover your card before passing the phone.',
    swipeFirst: 'Swipe up and remember your role.',
    continue: 'Your card is covered. Continue to the next player.',
    ready: 'EVERYONE KNOWS THEIR ROLE.', discuss: 'Your turn! Give clues, discuss and guess together.',
    unmask: 'Reveal imposters', impostersWere: 'THE IMPOSTERS WERE',
    back: 'Back to team', cancel: 'End round', cancelTitle: 'End this round?',
    cancelHint: 'This round will end. Your names and settings are kept.',
    cancelNo: 'Keep playing', cancelYes: 'End round',
    bombReady: '60 SECONDS. ONE TEAM.', bombIntro: 'Name matching footballers and pass the phone. The question appears when you start.',
    soundTest: 'Test sound', soundHint: 'Volume up. Keep the browser open during the round.',
    soundError: 'Could not start sound. Test the sound and try again.',
    soundRequired: 'Sound is enabled for this round before it starts.',
    running: 'THE BOMB IS TICKING', passBomb: 'Give an answer. Pass the phone!',
    finished: 'BOOM!', out: 'The player holding the phone is out.',
    time: 'Time remaining', loading: 'Enabling sound …',
    bombEasy: 'Clubs & nationalities', bombMedium: 'Nationality + position', bombHard: 'Teammates & career knowledge',
  },
} as const;
